#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr
setleds -D +num
picom &
#wal -i $waloc
nitrogen --restore
zsh ~/.config/polybar/launch.sh

bspc monitor -d I II III IV V

bspc config window_gap            6
bspc config border_width          4
bspc config focused_border_color  "#8a2be2"
#bspc config focused_border_color  "#ff0000"
bspc config normal_border_color  "#000000"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

