#! /bin/sh

#xrandr --output DP-1 --off --output HDMI-1 --off --output HDMI-2 --off --output HDMI-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --mode 1600x900 --pos 1920x0 --rotate normal
#xrandr --output DP-1 --off --output HDMI-1 --off --output HDMI-2 --off --output HDMI-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --mode 1600x900 --pos 1920x90 --rotate normal
# xrandr --output DP-1 --off --output HDMI-1 --off --output HDMI-2 --off --output HDMI-3 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --mode 1600x900 --pos 1920x180 --rotate normal

nitrogen --restore &
sh ~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
# picom &
# feh --recursive --bg-fill --randomize /home/xevil/Pictures/Wallpapers
#exec xautolock -time 5 -locker i3lock.sh &

bspc monitor VGA-1 -d 1 2 3 4 5 
bspc monitor HDMI-3 -d 1 2 3 4 5 
bspc monitor DP-2 -d firefox empty empty empty empty
# bspc monitor DP-2 -d "  " "  " "" "" " ﭮ "

bspc config window_gap            6
bspc config border_width          4
bspc config focused_border_color  "#8a2be2"
#bspc config focused_border_color  "#ff0000"
bspc config normal_border_color  "#000000"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

