# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃                                          Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.                                           ┃ #
# ┃                           Initialization code that may require console input must go above this block; everything else may go below.                              ┃ # 
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #
     if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
       source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
     fi
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃                                                                             functions                                                                             ┃ #
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #

    f           () { find . $1 | rg $1 }
    rb          () { curl cht.sh/ruby/$1 }
    gsd         () { git stash drop stash@{$1} }
    gpc         () { git push origin $1:$(gbc) }
    nif         () { file=$(fzf) && nvim "$file" }
    vif         () { file=$(fzf) && vim "$file" }
    des         () { docker exec -it $1 sh }
    dcs         () { docker compose exec -it $1 sh }
    dcr         () { docker compose down $1 ; docker compose up -d $1 }
    run         () { nohup $1 $2 > /dev/null & disown }
    tare        () { tar -xvf $1 }
    tarc        () { tar -cvzf $1.tar.gz $1 }
    ntfy        () { curl https://ntfy.dncp4312.dev/$(uname -n) -d "$*" }
    rcft        () { docker run -d cloudflare/cloudflared:latest tunnel --no-autoupdate run --token $CF_TOKEN }
    fdiff       () { diff -ru $1 $2 | diff-so-fancy }
    tex2pdf     () { docker run --rm -v "$PWD:/docs" -w /docs latex "$1" }
    brighten    () { echo $1 > /sys/class/backlight/amdgpu_bl0/brightness }
    depends     () { awk '/Required/{for (i=4;i<NF+1;++i) print $i}' <(pQ -i $1) }
    colormap    () { for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done }
    show_colour () { perl -e 'foreach $a(@ARGV){print "\e[48:2::".join(":",unpack("C*",pack("H*",$a)))."m \e[49m "};print "\n"' "$@" }
    installed   () { awk '/%NAME%/{getline;PKG=$1} /%INSTALLDATE%/{getline;IDATE=strftime("%Y-%m-%d %H:%M",$1);print IDATE" "PKG}' /var/lib/pacman/local/*/desc|sort }
    xget        () { cp $(which $1) $HOME/.local/xbin/ }
    fcd         () { dir=$(find -type d | fzf) || return ; 
		     clear ; echo "\033[0;30mCurrent Directory :\033[0m"   
		     cd "$dir" ; exa --group-directories-first --color=always }
    setlive     () { echo $(readlink -f $1) > $XDG_CONFIG_HOME/live ; bspc wm -r }
    png_to_b64  () { cat <(echo '  background-image: url(data:image/png;base64,') <(echo "$(convert $1 -resize $2x$2 png:- | base64)") <(echo ');') | tr -d '\n' > $(echo $1 | sed 's/.png//') }
    bt          () { local mac=$(bluetoothctl devices | grep -i "$2" | awk '{print $2}' | head -1) ; [[ -n "$mac" ]] && bluetoothctl "$1" "$mac" }
    # gpl         () { git branch -r --merged | tr -d " " | grep origin | sed "s/origin\///" | grep -Ev "(^\*|master|development|staging|^$(git branch --show-current))" | xargs git branch --delete }
    gbp         () { LBUFFER+=$(git branch | fzf --no-preview | tr -d '[* ]' || echo) ; zle redisplay }
    gpl         () { git branch --merged | tr -d " " | sed "s/origin\///" | grep -Ev "(^\*|master|development|staging|^$(git branch --show-current))" | xargs git branch --delete }

    # decode_jwt  () { cut -d"." -f2 <<< $1 | base64 --decode | jq }
    decode_jwt() {
    IFS='.' read -r part1 part2 part3 <<< "$1"
	echo "$part1" | tr -d '\n' | base64 --decode | jq
	echo "$part2" | tr -d '\n' | base64 --decode | jq
	echo "$part3" | tr -d '\n' | base64 --decode | jq
    }

    rv() { selection=$(rg $1 --vimgrep | fzf)
	   line=$(echo $selection| cut -d: -f2)
	   file=$(echo $selection| cut -d: -f1)
	   vim +$line $file
	 }

    list() { emulate -L zsh ; clear ; exa --group-directories-first }

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃                                                                              widgets                                                                              ┃ #
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #

    zle -N gbp

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃                                                                             shortcuts                                                                             ┃ #
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #
    bindkey '^y' 'gbp'

    # bindkey -s '^o' 'vim $(fzf) ^M'
    bindkey -s '^b' 'gcf ^M'
    bindkey -s '^n' 'gcfr ^M'
    bindkey -s '^j' 'gbm ^M'
    bindkey -s '^p' 'vif ^M'
    bindkey -s '^k' 'nif ^M'
    bindkey -s '^g' 'fcd ^M'
    bindkey -s '^w' 'sysres iwd ^M'
    bindkey -s '^[p' 'ping -c8 1.1.1.1 ^M'

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃                                                                              sources                                                                              ┃ #
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #
    # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
    [[ ! -f $ZDOTDIR/grml.zsh ]] || source $ZDOTDIR/grml.zsh
    [[ ! -f $ZDOTDIR/aliases  ]] || source $ZDOTDIR/aliases
    [[ ! -f $ZDOTDIR/ekke.zsh ]] || source $ZDOTDIR/ekke.zsh
    [[ ! -f $ZDOTDIR/p10k.zsh ]] || source $ZDOTDIR/p10k.zsh ; source $ZDOTDIR/.p10k/powerlevel10k.zsh-theme
    [[ ! -f /usr/share/fzf/key-bindings.zsh ]] || source /usr/share/fzf/key-bindings.zsh
    # [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓ #
# ┃                                                                           customizations                                                                          ┃ #
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛ #

    terminaltheme.sh xeha 

    autoload -U select-word-style
    select-word-style default
    WORDCHARS='*?[]~=&;!#$%^(){}<>'

    # plugins=(git-auto-fetch)
    # chpwd_functions=(${chpwd_functions[@]} "list")

    # alias sl=setlive
    # alias sc=' cd ~/.cache/styli.sh'
    # alias ew=' vim ~/.local/bin/styli.sh'
    export local_ip=$(ipl | cut -d\/ -f1)
    # ol() { echo "(79.56 - $1) * 285" | bc; }
